### ISSUE TITLE
Permettre aux options de l'écran de login de défiler

### ISSUE THREAD

**Issue by locness3** [ecnivtwelve/Papillon#11]
C'est probablment que sur firefox mais bon 💀![Screenshot_20220905-235553.png](https://user-images.githubusercontent.com/37651007/188515677-f30d96a8-629c-4049-8a25-beff1a2469d9.png)

**Comment by ecnivtwelve** [comment]
fixé dans https://github.com/ecnivtwelve/Papillon/commit/63ea328f87ed78f6466e23c7c1198c166bc06864
