### ISSUE TITLE
Problème affichage des devoirs

### ISSUE THREAD

**Issue by Astrow25** [ecnivtwelve/Papillon#12]
L'affichage sous 5 jours est bugué quand on passe à la prochaine semaine (on devrait plus le faire par semaine) + affichage des devoirs en boucle sur certains jours (ici la physique)
https://user-images.githubusercontent.com/76118368/188609033-2b727609-85af-4ca5-b920-5cc1d8e004bb.mp4

**Comment by ecnivtwelve** [comment]
fixé avec la nouvelle interface (https://github.com/ecnivtwelve/Papillon/commit/a26fd9ed7babee62032a8f2fd8b2c550d5bbd8db)
