### ISSUE TITLE
Connection impossible

### ISSUE THREAD

**Issue by AnonymeDuScript** [ecnivtwelve/Papillon#13]
Bonjour, 

Je n'arrive pas a me connecter a mon college du val d'oise je pense que cela doit atre a cause de la modification de connection, depuis le debut d'année le lien enregistrer dans le json (https://cas.moncollege.valdoise.fr/login) et celui ou il faut choisir entre Parent Eleve Vie sco... pouvais mettre celui des éléve (https://cas.moncollege.valdoise.fr/login?selection=eleveparent) 

Merci d'avance

**Comment by AnonymeDuScript** [comment]
Aprés quelque recherche je remarque que le nouveux systeme pour l'ent a changer pour les ent crée par skolengo

**Comment by locness3** [comment]
@ecnivtwelve

**Comment by ecnivtwelve** [comment]
ça va être difficile à fix vu que je dev pas la prise en charge des ent dans pronote-api...

**Comment by ecnivtwelve** [comment]
--> problème d'api / pas fixable
