### ISSUE TITLE
Alerte flux rss

### ISSUE THREAD

**Issue by tryon-dev** [ecnivtwelve/Papillon#15]
j'aimerais bien avoir une notification a partir d'un flux rss
voici une preview faite en 1 minute

![image](https://user-images.githubusercontent.com/68423470/189211198-98a63e81-42c5-400a-aae0-7c7c1ee65f93.png)

**Comment by locness3** [comment]
genre tu veux suivre un flux rss depuis pronote+?

**Comment by ecnivtwelve** [comment]
Je pense qu'il faudrait move ca dans les (futures) extensions
