### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Astrow25** [ecnivtwelve/Papillon#16]
Fix l'entièreté des bugs sur Android : 
- logo Pronote de mauvaise couleur
- la non mise a jour (même par force)
- ...

**Comment by ecnivtwelve** [comment]
deverait être fix ici https://github.com/ecnivtwelve/Papillon/commit/58c58084e54b80a29b40f74412a991d955c6762a, hésitez pas à reopen

**Comment by locness3** [comment]
on peut pas reopen bg 💀

**Comment by ecnivtwelve** [comment]
vous demanderez à reopen ou ferez une new issue au pire 💀

**Comment by locness3** [comment]
ok
