### ISSUE TITLE
Le bouton retour se transforme en bouton menu avant d'être sur la vue principale

### ISSUE THREAD

**Issue by locness3** [ecnivtwelve/Papillon#2]
Paramètres > Personnaliser l'interface > Changer de police.. > Retour -> le bouton retour devient un bouton menu

**Comment by ecnivtwelve** [comment]
c'est plus un workaround qu'un fix mais https://github.com/ecnivtwelve/Papillon/commit/6d9aa257abdfafd766a73906077d19bbd31696fd fait en sorte de revenir aux paramètres
