### ISSUE TITLE
Le bouton jour suivant avance de deux jours si l'on affiche le cahier de textes

### ISSUE THREAD

**Issue by locness3** [ecnivtwelve/Papillon#3]
1. Sélectionner une date dans le menu et ouvrir l'emploi du temps
-> affiche l'edt de la date sélectionnée
2. Ouvrir le menu et utiliser le bouton Suivant dans la date
-> la date avance d'un jour comme attendu

1. Sélectionner une date dans le menu et ouvrir le cahier de textes
-> affiche le cdt du lendemain, probablement logique
2. Ouvrir le menu
-> la date affichée est celle sélectionnée précédemment
3. Utiliser le bouton Suivant dans la date
-> la date avance de 2 jours, soit un jour par rapport à la date affichée dans le cdt

**Comment by ecnivtwelve** [comment]
fixé dans https://github.com/ecnivtwelve/Papillon/commit/e0f766e4d471d88c3c2907434bcc344522a49c41
