### ISSUE TITLE
Si l'utilisateur n'a pas de photo de profil ça affiche l'image bug du navigateur

### ISSUE THREAD

**Issue by locness3** [ecnivtwelve/Papillon#4]

**Comment by Astrow25** [comment]
![image](https://user-images.githubusercontent.com/76118368/188282161-f34e681c-8fe4-43f6-925d-ba0ef23d6887.png)

**Comment by ecnivtwelve** [comment]
fixé dans https://github.com/ecnivtwelve/Papillon/commit/366d97a4580742c7cab353ec6bfe5d02558354b2
