### ISSUE TITLE
Propositions pour MAJ.

### ISSUE THREAD

**Issue by mortadhagh** [ecnivtwelve/Papillon#6]
- Permettre aux utilisateurs d'ajouter des exercices à faire dans la catégorie "travail à faire".

- D'ajouter manuellement une photo de profil.

**Comment by Astrow25** [comment]
Les propositions de maj doivent être écritent dans un pull request, cela nous permet de gérer et de trier plus facilement les bugs / des suggestions.
Merci d'ouvrir un pull request

**Comment by locness3** [comment]
Les pull request sont des demandes d'ajouts de code. À moins de proposer une implémentation d'une fonctionnalité, l'endroit pour la proposer est dans les issues, ou sur Discord (je ne sais pas si @ecnivtwelve à une préférence)

**Comment by locness3** [comment]
> - Permettre aux utilisateurs d'ajouter des exercices à faire dans la catégorie "travail à faire".
> 
> - D'ajouter manuellement une photo de profil.

Par ailleurs, chaque proposition devrait avoir une issue différente pour mieux en suivre l'avancement

**Comment by mortadhagh** [comment]
D'accord, je vais le faire. 
Merci pour vos réponses.
