### ISSUE TITLE
Ouvrir les actus force une reconnexion

### ISSUE THREAD

**Issue by Rexxt** [ecnivtwelve/Papillon#8]
Ouvrir les actualités force une reconnexion en arrière plan avant d'afficher l'écran de connexion et de retenter de se connecter.

**Comment by ecnivtwelve** [comment]
![image](https://user-images.githubusercontent.com/32978709/188309030-c3bfef0f-6393-4e91-8c16-9ddad10418f1.png)
hm étrange

**Comment by ecnivtwelve** [comment]
@Rexxt comment reproduirais-tu cette issue ?

**Comment by Rexxt** [comment]
aller dans le menu -> cliquer sur agenda -> l'appli tente de reconnecter

**Comment by Rexxt** [comment]
edit : c'est les actus, pas l'agenda

**Comment by locness3** [comment]
Confirmé.

**Comment by ecnivtwelve** [comment]
fixé dans https://github.com/ecnivtwelve/Papillon/commit/3f7fdb6359399be0ce5d6094a4d4ace71d7cb7e7
